### ISSUE TITLE
Stylish Beats: Markbot is expecting to see a width with a different value inside img {}

### ISSUE THREAD

**Issue by sent0007** [sent0007/stylish-beets#1]
I've been scaling my image to different sizes to try and fit markbots specifications for the assignment, but I can't seem to hit the right target size. It seems exact when it comes to the width. I've tried rem units and pixels. Neither seem to work. 

Can you think of anything that might be causing the issue?  @thomasjbradley 
https://github.com/sent0007/stylish-beets/blob/gh-pages/css/main.css#L35-L38

Thanks,
Curtis

![Screen Shot 2019-10-06 at 7 09 47 PM](https://user-images.githubusercontent.com/55108791/66277516-a6430480-e86d-11e9-8a29-13f0df7a7306.png)
![Screen Shot 2019-10-06 at 7 09 13 PM](https://user-images.githubusercontent.com/55108791/66277517-a6430480-e86d-11e9-904c-ce09e8479c29.png)
![Screen Shot 2019-10-06 at 7 09 05 PM](https://user-images.githubusercontent.com/55108791/66277518-a6430480-e86d-11e9-90ee-c64a465c117d.png)

**Comment by thomasjbradley** [comment]
Markbot is looking for the width to be `100%`, like shown in the intro slide deck.

**Comment by sent0007** [comment]
Oh wow, can't believe i missed that. Thank you!!
